apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ft-services
    tier: ftps
spec:
  type: NodePort
  selector:
    app: ft-services
    tier: ftps
  ports:
  - name: ftps
    protocol: TCP
    port: 21
    nodePort: 21
  - name: ftps-data
    protocol: TCP
    port: 30021
    nodePort: 30021
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ft-services
    tier: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-services
      tier: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft-services
        tier: ftps
    spec:
      restartPolicy: Always
      containers:
      - image: my-ftps
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          #hostPort: 21
        - containerPort: 30021
          #hostPort: 30021
        #- containerPort: 30020
        #  hostPort: 30020
        #- containerPort: 30021
        #  hostPort: 30021
        env:
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ftps
              key: username
        - name: FTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps
              key: password
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
