apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: ft-services
    tier: grafana
spec:
  type: NodePort
  selector:
    app: ft-services
    tier: grafana
  ports:
  - port: 3000
    nodePort: 3000
    name: http
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ft-services
    tier: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-services
      tier: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft-services
        tier: grafana
    spec:
      restartPolicy: Always
      containers:
      - image: my-grafana
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
