apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: ft-services
    tier: influxdb
spec:
  type: NodePort
  selector:
    app: ft-services
    tier: influxdb
  ports:
  - port: 8086
    nodePort: 8086
    protocol: TCP
    name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ft-services
    tier: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-services
      tier: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft-services
        tier: influxdb
    spec:
      restartPolicy: Always
      containers:
      - image: my-influxdb
        name: influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
