apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft-services
    tier: mysql
spec:
  selector:
    app: ft-services
    tier: mysql
  ports:
  - port: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ft-services
    tier: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-services
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft-services
        tier: mysql
    spec:
      restartPolicy: Always
      containers:
      - image: my-mysql
        name: mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT
          valueFrom:
            secretKeyRef:
              name: mysql
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
