apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: ft-services
    tier: nginx
spec:
  selector:
    app: ft-services
    tier: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ssh
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 30022
      targetPort: 30022
      nodePort: 30022
      protocol: TCP
  selector:
    app: ft-services
    tier: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ft-services
    tier: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-services
      tier: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft-services
        tier: nginx
    spec:
      containers:
      - image: my-nginx
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 30022
          name: ssh
        env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: ssh
              key: username
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh
              key: password
