apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: ft-services
    tier: telegraf
spec:
  selector:
    app: ft-services
    tier: telegraf
  type: NodePort
  ports:
  - port: 8125
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ft-services
    tier: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-services
      tier: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft-services
        tier: telegraf
    spec:
      restartPolicy: Always
      containers:
      - image: my-telegraf
        name: telegraf
        imagePullPolicy: Never
        env:
        - name: USER
          value: telegraf
        - name: INFLUX_URL
          value: "http://#MINIKUBE_IP#:8086"
        - name: INFLUX_SKIP_DATABSE_CREATION
          value: "false"
        - name: INFLUX_PASSWORD
          value: pwdinflux
        volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
